ui:
  theme: dark
  logo_path: assets/logo.png

document:
  template_path: docx-template/
  templates:
    laptops:
      file_name: TERMO DE RESPONSABILIDADES NOTEBOOKS.docx
      placeholders:
        - name: "[LAPTOPMODEL]"
          type: text
          category: "Laptops"
          description: "Modelo do laptop"
          default: false
          required: true
          identifier: false
          source:
            type: asset
            format: "{model} - {asset_tag} - {serial}"
          generates_presence_marker: true
          presence_marker_value: "X" 
        - name: "[MOUSEMODEL]"
          type: text
          category: "Mouses"
          description: "Modelo do mouse"
          default: false
          required: false
          identifier: false
          source:
            type: accessories
            path: name
          generates_presence_marker: true
          presence_marker_value: "X"
        - name: "[KEYBOARDMODEL]"
          type: text
          category: "Keyboards"
          description: "Modelo do teclado"
          default: false
          required: false
          identifier: false
          source:
            type: accessories
            path: name
          generates_presence_marker: true
          presence_marker_value: "X"
        - name: "[MONITORMODEL]"
          type: text
          category: "Monitors"
          description: "Modelo do monitor"
          default: false
          required: false
          identifier: false
          source:
            type: accessories
            path: name
          generates_presence_marker: true
          presence_marker_value: "X"
        - name: "[CHARGERMODEL]"
          type: text
          category: "Charger"
          description: "Modelo do carregador"
          default: false
          required: false
          identifier: false
          source:
            type: accessories
            path: name
          generates_presence_marker: true
          presence_marker_value: "X"
        - name: "[HEADSETMODEL]"
          type: text
          category: "Headsets"
          description: "Modelo do headset"
          default: false
          required: false
          identifier: false
          source:
            type: accessories
            path: name
          generates_presence_marker: true
          presence_marker_value: "X"
        

    smartphones:
      file_name: TERMO DE RESPONSABILIDADES CELULARES.docx
      
      placeholders:
        - name: "[SMARTPHONEMODEL]"
          type: text
          category: "Smartphones"
          description: "Modelo do smartphone"
          default: false
          required: true
          identifier: false
          source:
            type: asset
            format: "{model}"
          generates_presence_marker: true
          presence_marker_value: "X"
        - name: "[CHARGERMODEL]"
          type: text
          category: "Charger"
          description: "Modelo do carregador"
          default: false
          required: false
          identifier: false
          source:
            type: accessories
            path: name
          generates_presence_marker: true
          presence_marker_value: "X"
        - name: "[SIMCARDMODEL]"
          type: text
          category: "SIM Card"
          description: "Modelo do chip"
          default: false
          required: false
          identifier: false
          source:
            type: components
            format: "{name} - {numero_do_celular}" 
          generates_presence_marker: true
          presence_marker_value: "X"

  default_placeholders:
    - name: "[NAME]"
      type: text
      category: "User Information"
      description: "Nome do usuário"
      default: false
      required: true
      identifier: false
      source:
        type: text
        path: name
    - name: "[EMPLOYEE_NUMBER]"
      type: text
      category: "User Information"
      description: "Matrícula do usuário"
      default: false
      required: true
      identifier: true
      source:
        type: text
        path: employee_num