ui:
  theme: dark
  logo_path: assets/logo.png

document:
  template_path: docx-template/
  templates:
    laptops:
      file_name: TERMO DE RESPONSABILIDADES NOTEBOOKS.docx
      display_names:
        categories:
          Charger: Carregador
          Monitors: Monitor
          Mouses: Mouse
          Keyboards: Teclado
          Headsets: Headset

    smartphones:
      file_name: TERMO DE RESPONSABILIDADES CELULARES.docx
      display_names:
        categories:
          Charger: Carregador
          SIM Card: SIM Card