ui:
  theme: dark
  logo_path: assets/logo.png

document:
  template_path: docx-template/
  templates:
    termo_de_responsabilidade:
      file_name: TERMO DE RESPONSABILIDADES NOTEBOOKS.docx
      description: Template master de responsabilidades e devolucao
      display_names:
        categories:
          Charger: Carregador
          Monitors: Monitor
          Mouses: Mouse
          Keyboards: Teclado
          Headsets: Headset
          SIM Card: SIM Card
