ui:
  theme: dark
  logo_path: assets/logo.png

document:
  template_path: docx-template/
  templates:
    laptops:
      file_name: TERMO DE RESPONSABILIDADES NOTEBOOKS.docx
      placeholders:
        - name: "[LAPTOPMODEL]"
          type: text
          category: "Laptops"
          description: "Modelo do laptop"
          default: false
          required: true
          identifier: false
          source:
            type: asset
            format: "{model} - {asset_tag} - {serial}" 
        - name: "[MOUSEMODEL]"
          type: text
          category: "Mouses"
          description: "Modelo do mouse"
          default: false
          required: false
          identifier: false
          source:
            type: accessories
            path: name
        - name: "[KEYBOARDMODEL]"
          type: text
          category: "Keyboards"
          description: "Modelo do teclado"
          default: false
          required: false
          identifier: false
          source:
            type: accessories
            path: name
        - name: "[MONITORMODEL]"
          type: text
          category: "Monitors"
          description: "Modelo do monitor"
          default: false
          required: false
          identifier: false
          source:
            type: accessories
            path: name
        - name: "[CHARGERMODEL]"
          type: text
          category: "Charger"
          description: "Modelo do carregador"
          default: false
          required: false
          identifier: false
          source:
            type: accessories
            path: name
        - name: "[HEADSETMODEL]"
          type: text
          category: "Headsets"
          description: "Modelo do headset"
          default: false
          required: false
          identifier: false
          source:
            type: accessories
            path: name
        - name: "[HASLAPTOP]"
          type: bool
          category: "Laptops"
          description: "Possui laptop?"
          default: false
          required: true
          identifier: false
          source:
            type: literal
            value: "X"
        - name: "[HASMOUSE]"
          type: bool
          category: "Mouses"
          description: "Possui mouse?"
          default: false
          required: false
          identifier: false
          source:
            type: literal
            value: "X"
        - name: "[HASCHARGER]"
          type: bool
          category: "Charger"
          description: "Possui charger?"
          default: false
          required: false
          identifier: false
          source:
            type: literal
            value: "X"
        - name: "[HASKEYBOARD]"
          type: bool
          category: "Keyboards"
          description: "Possui teclado?"
          default: false
          required: false
          identifier: false
          source:
            type: literal
            value: "X"
        - name: "[HASHEADSET]"
          type: bool
          category: "Headsets"
          description: "Possui headset?"
          default: false
          required: false
          identifier: false
          source:
            type: literal
            value: "X"
        - name: "[HASMONITOR]"
          type: bool
          category: "Monitors"
          description: "Possui monitor?"
          default: false
          required: false
          identifier: false
          source:
            type: literal
            value: "X"

    smartphones:
      file_name: TERMO DE RESPONSABILIDADES CELULARES.docx
      
      placeholders:
        - name: "[SMARTPHONEMODEL]"
          type: text
          category: "Smartphones"
          description: "Modelo do smartphone"
          default: false
          required: true
          identifier: false
          source:
            type: asset
            format: "{model.name}"
        - name: "[CHARGERMODEL]"
          type: text
          category: "Charger"
          description: "Modelo do carregador"
          default: false
          required: false
          identifier: false
          source:
            type: accessories
            path: name
        - name: "[SIMCARDMODEL]"
          type: text
          category: "SIM Card"
          description: "Modelo do chip"
          default: false
          required: false
          identifier: false
          source:
            type: components
            path: name
        - name: "[HASSMARTPHONE]"
          type: bool
          category: "Smartphones"
          description: "Possui smartphone?"
          default: false
          required: true
          identifier: false
          source:
            type: literal
            value: "X"
        - name: "[HASCHARGER]"
          type: bool
          category: "Charger"
          description: "Possui carregador?"
          default: false
          required: false
          identifier: false
          source:
            type: literal
            value: "X"
        - name: "[HASSIMCARD]"
          type: bool
          category: "SIM Card"
          description: "Possui chip?"
          default: false
          required: false
          identifier: false
          source:
            type: literal
            value: "X"

  default_placeholders:
    - name: "[NAME]"
      type: text
      category: "User Information"
      description: "Nome do usuário"
      default: false
      required: true
      identifier: false
      source:
        type: text
        path: user_name
    - name: "[EMPLOYEE_NUMBER]"
      type: text
      category: "User Information"
      description: "Matrícula do usuário"
      default: false
      required: true
      identifier: true
      source:
        type: text
        path: employee_number