[tool.ruff]
line-length = 100                # Máximo de 100 caracteres por linha
target-version = "py39"         # Compatível com Python 3.9
exclude = ["tests", ".venv", "migrations"]  # Ignora essas pastas

# Regras ativadas (você pode adicionar mais depois se quiser)
lint.select = [
  "E",   # Erros do pycodestyle
  "F",   # pyflakes (erros de variáveis, imports não usados)
  "I",   # isort (organização de imports)
  "UP",  # pyupgrade (sugestões para usar recursos modernos)
  "B",   # bugbear (boas práticas e problemas comuns)
]

# Corrige automaticamente onde possível com `--fix`
fix = true
