[tool.ruff]
line-length = 100                # Máximo de 100 caracteres por linha
target-version = "py311"         # Compatível com Python 3.9
exclude = ["__pycache__", "tests", "dist"]  # Ignora essas pastas

# Regras ativadas 
lint.select = [
  "E",   # Erros do pycodestyle
  "F",   # pyflakes (erros de variáveis, imports não usados)
  "I",   # isort (organização de imports)
  "UP",  # pyupgrade (sugestões para usar recursos modernos)
  "B",   # bugbear (boas práticas e problemas comuns)
]

# Corrige automaticamente onde possível com `--fix`
fix = true

[tool.mypy]
python_version = 3.11
exclude = ["tests", "venv", "build", "dist"]
ignore_missing_imports = true
check_untyped_defs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
warn_unused_configs = true

[[tool.mypy.overrides]]
module = "yaml"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "requests"
ignore_missing_imports = true