name: Verificação de Qualidade e Testes
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python
        with:
          python-version: '3.11'
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      - name: Verificar formatação e linting com Ruff
        run: |
          ruff format --check
          ruff check .
      - name: Rodar testes com Pytest
        run: pytest --cov=.
